Q.2. Refer to salaries.xlsx file and solve following questions
1. Check head of the dataframe
2. Find out details about no. of entries & no. of columns in the data frame
3. What is the average base pay?
4. What is the highest amount of overtime pay in the dataset?
5. What is the job title of JOSEPH DRISCOLL?
6. How much does JOSEPH DRISCOLL make (including benefits)?
7. How many unique job titles are there?
8. What are the top 5 common jobs?

In [5]:
import numpy as np

In [6]:
import pandas as pd

In [9]:
data = pd.read_excel("C:/Users/chait/OneDrive/Desktop/FBS/Data Analysis/Datasets/Datasets/Salaries.xlsx")
data

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,ANTIONETTE GRIFFIN,CLINICAL NURSE SPECIALIST,169572.08,0.00,250.00,NaN,169822.08,169822.08,2011,NaN,San Francisco,NaN
996,997,KATHERINE MAH,CLINICAL NURSE SPECIALIST,169572.06,0.00,250.00,NaN,169822.06,169822.06,2011,NaN,San Francisco,NaN
997,998,CHRISTINE DAVENPORT,CLINICAL NURSE SPECIALIST,169572.05,0.00,250.00,NaN,169822.05,169822.05,2011,NaN,San Francisco,NaN
998,999,ANNE HUGHES,CLINICAL NURSE SPECIALIST,169572.01,0.00,250.00,NaN,169822.01,169822.01,2011,NaN,San Francisco,NaN
999,1000,JOHN FAZIO,CLINICAL NURSE SPECIALIST,169572.00,0.00,250.00,NaN,169822.00,169822.00,2011,NaN,San Francisco,NaN

In [10]:
data.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                1000 non-null   int64
 1   EmployeeName      1000 non-null   str
 2   JobTitle          1000 non-null   str
 3   BasePay           1000 non-null   float64
 4   OvertimePay       1000 non-null   float64
 5   OtherPay          1000 non-null   float64
 6   Benefits          0 non-null      float64
 7   TotalPay          1000 non-null   float64
 8   TotalPayBenefits  1000 non-null   float64
 9   Year              1000 non-null   int64
 10  Notes             0 non-null      float64
 11  Agency            1000 non-null   str
 12  Status            0 non-null      float64
dtypes: float64(8), int64(2), str(3)
memory usage: 101.7 KB

In [12]:
data.shape

(1000, 13)

In [13]:
data['BasePay'].mean()

np.float64(145663.9982)

In [15]:
data['OvertimePay'].max()

np.float64(245131.88)

In [16]:
data[data['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

In [17]:
data[data['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [18]:
data['JobTitle'].nunique()

113

In [19]:
data['JobTitle'].value_counts().head(5)

JobTitle
FIREFIGHTER                           133
LIEUTENANT, FIRE DEPARTMENT            62
FIRE FIGHTER PARAMEDIC                 43
CAPTAIN, FIRE SUPPRESSION              42
BATTALION CHIEF, (FIRE DEPARTMENT)     41
Name: count, dtype: int64